# Setup
title:               MonarchToMintToReport
tagline:             'A simple tool to convert between accounting app file formats'
description:         '<a href="https://github.com/mwengren/monarchtominttoreport"><img width="30" src="public/img/github-mark.png" /> MonarchToMintToReport</a>' 
url:                 https://mwengren.github.io
baseurl:             '/monarchtominttoreport'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Micah Wengren
  url:               https://mwengren.github.io
  email:             micah.wengren@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             0.2a5
google_analytics_id: #UA-XXXX-Y
